[versions]
# libraries
gson= "2.13.2"

# plugins
changelog = "2.4.0"
intellijPlatform = "2.10.1"
kotlin = "2.2.0"
ktlint = "13.1.0"

[libraries]
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intellijPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intellijPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
